version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./script/rabbitmq/rabbitmq-enabled-plugins:/etc/rabbitmq/enabled_plugins
      - ./script/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./script/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

  postgres:
    container_name: postgress
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=audit
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./script/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql