sas:
  messaging:
    rabbitmq:
      host: localhost
      virtual-host: /
      port: 5672
      username: guest
      password: guest
      exchange:
        request: sas-request-exchange
        reply: sas-reply-exchange
        heartbeat: sas-heartbeat-exchange
      routing-key:
        request: sas-request
        reply: sas-reply
        heartbeat: sas-heartbeat